---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouncer
  namespace: bouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bouncer
  template:
    metadata:
      labels:
        app: bouncer
    spec:
      containers:
        - name: bouncer
          image: camelel/bouncer:latest
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: bouncer-tls
